### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by esteiert**
Reformatting txt files into list of sentence lists

### CODE REVIEW

**Comment by TylerKirby** [comment]
Are these the same files that were added in #1 ?

**Comment by esteiert** [comment]
The first files are the same Perseus texts as #1, but in the [[('word', 'tag')...] format instead of word/tag. The second group of files are the PROIEL texts as word/tag.

**Comment by TylerKirby** [comment]
Ah ok I see cool. Let's keep the PROIEL word/tag texts in this pull request then. Then to fulfill [this](https://trello.com/c/35jNRZMK/2-write-data-set-parsing-function) ticket, just include the Python file with the code used to transform from word/tag to [[('word', 'tag')...].

**Comment by esteiert** [comment]
The Python file for the Perseus transformation is in the first group of files, but that code ran into some problems with the PROIEL set because it has some forms with spaces in them. I ended up writing another version for the PROIEL set that went straight from XML into [[('word', 'tag')...] instead — do we need specifically from the word/tag .txt format?

**Comment by TylerKirby** [comment]
Ok I see that now. For our first set of models, we need the word/tag format. For the second set, we will use the [[('word', 'tag')...] format. The word/tag format will be our 'source of truth' for the project and any variations required will be handled by scripts. You bring up a good point about the spaces in the tags. We need them all to be the same length strings and we do not want to deal with meaningful white space, so let's replace the spaces in the tags with `-`. E.g., `v3a1s   ` should be `v3a1s---`.

So let's do the following:
- Remove the [[('word', 'tag')...] version of Perseus files from the pull request. We will use the code in the notebook to handle these transformations when we need them.
- Add word/tag versions of the PROIEL texts. Spaces in tags become `-`.

The final pull request should contain only word/tag versions of the PROIEL texts and the notebook used to convert word/tag to [[('word', 'tag')...] .

**Comment by esteiert** [comment]
Oh, I meant spaces in the words themselves, like counting "ducenta quadraginta" as one word. But I should be able to figure something out with that, and once I do, I'll make these changes to the pull request!

**Comment by esteiert** [comment]
Do we want to retain spaces in words (like "ducenta quadraginta") for the word/tag format?

**Comment by TylerKirby** [comment]
We should. To make things easier/consistent, let's replace the space between those types of words with `_`. E.g., `ducenta quadraginta` -> `ducenta_quadraginta`

**Pull request closed without merging**
